name: Spyglass Apply

on:
  push:
    branches: [master]

jobs:
  spyglass_job:
    runs-on: ubuntu-latest
    name: Apply
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install spyglass CLI
        run: npm install -g spyglass-cli

      - name: Apply spyglass configuration to production
        run: spyglass apply skigdyn-wu58851 --git-ref "${{ github.event.before }}" --dir spyglass --dry-run
        env:
          SNOWSQL_CONFIG: ${{ secrets.SNOWSQL_CONFIG }}

