name: all-tests
on:
  workflow_dispatch:

jobs:
  all-tests:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node_version: [lts/*]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - run: npm ci
      - run: |
          mkdir -p ~/.snowsql
          echo "$SNOWSQL_CONFIG" > "$HOME/.snowsql/config"
          npm run cover
        env:
          SNOWSQL_CONFIG: ${{ secrets.SNOWSQL_CONFIG }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
