name: Release and Publish
on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Semantic version increment type. Patch (v1.2.4), Minor (v1.3.0), Major (v2.0.0)'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node_version: [lts/*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - run: npm ci

      - name: Git commit and push
        shell: bash
        run: |
          git config --global user.name 'spyglass-software'
          git config --global user.email 'devs@spyglass.software'
          ./scripts/release.sh "${{ inputs.versionType }}"
          git show HEAD
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      # - run: npm run cover
      #   env:
      #     SNOWSQL_CONFIG: ${{ secrets.SNOWSQL_CONFIG }}

      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
