name: Release and Publish
on:
  workflow_dispatch:
    inputs:
      versionType:
        description: 'Semantic version increment type. Patch (v1.2.4), Minor (v1.3.0), Major (v2.0.0)'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node_version: [lts/*]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - run: npm ci

      - run: npm run cover
        env:
          SNOWSQL_CONFIG: ${{ secrets.SNOWSQL_CONFIG }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Git commit and push
        shell: bash
        run: |
          git config --global user.name 'spyglass-software'
          git config --global user.email 'devs@spyglass.software'
          ./scripts/release.sh "${{ inputs.versionType }}"
          git show HEAD
          git push
          git push --tags
        env:
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Create the docs directory locally in CI
        run: npx typedoc src/lib/index.ts

      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs
