on: [push]

jobs:
  spyglass_job:
    runs-on: ubuntu-latest
    name: Spyglass apply job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install spyglass
        run: npm install -g spyglass-cli
      - name: Spyglass test
        run: spyglass apply --dry-run skigdyn-wu58851
