on: [push]

jobs:
  spyglass_job:
    runs-on: ubuntu-latest
    name: Spyglass merge
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install spyglass CLI
        run: npm install -g spyglass-cli

      - name: Apply spyglass configuration to production
        run: spyglass apply --dry-run skigdyn-wu58851 --git-ref "${{ github.event.before }}"
